packages:
  - apps/*
  - docs/*
  - packages/*

catalog:
  "@biomejs/biome": ^1.9.4
  "@ponder/utils": 0.2.8
  "@types/node": ^22.14.0
  "@vitest/coverage-v8": ^3.1.1
  drizzle-orm: =0.41.0
  hono: ^4.7.6
  typescript: ^5.7.3
  viem: ^2.22.13
  vitest: ^3.1.1
  ponder: 0.11.25
  tsup: ^8.3.6
  "@astrojs/react": ^4.2.0
  "@astrojs/tailwind": ^6.0.0
  "astro-font": ^1.0.0
  "astro-seo": ^0.8.4
  "@namehash/namekit-react": 0.12.0
