services:
  ensadmin:
    container_name: ensadmin
    image: ghcr.io/namehash/ensnode/ensadmin:${ENSNODE_VERSION:-1.11.0}
    build:
      dockerfile: ./apps/ensadmin/Dockerfile
      context: ../..
    ports:
      - "4173:4173"
