services:
  ensindexer:
    container_name: ensindexer
    image: ghcr.io/namehash/ensnode/ensindexer:${ENSNODE_VERSION:-1.11.0}
    build:
      dockerfile: ./apps/ensindexer/Dockerfile
      context: ../..
    ports:
      - "42069:42069"
    healthcheck:
      test: ["CMD", "curl", "--fail", "-s", "http://localhost:42069/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5m
      start_interval: 1s
